version: "3"

services:
  db:
    container_name: kamino-database
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'kamino'
      MYSQL_USER: 'kamino-user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data-db:/var/lib/mysql
  server:
    container_name: kamino-server
    build:
      context: ./server
    environment:
      SECRET: 'this is a super secret'
      CORS_ORIGIN: '*'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_USER: 'kamino-user'
      DB_PASSWORD: 'password'
      DB_SCHEMA: 'kamino'
      PORT: '8080'
      FORCE_DB_SYNC: 'false'
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/api/ping || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
volumes:
  data-db:
