import Head from "next/head";
import { Inter } from "next/font/google";
import App from "./App";
import styles from "@/styles/general.module.css";
const inter = Inter({ subsets: ["latin"] });
import Nav from "@/components/Nav";

export default function index() {
  return (
    <>
      <Head>
        <title>Project-1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <App />
     
    </>
  );
}
