name: Trigger auto deployment for test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'client/**'
    - '.github/workflows/test-AutoDeployTrigger-b71ba2ca-5c9e-420c-bd53-fa36b33cfeb6.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/client 
          registryUrl: scipio.azurecr.io
          registryUsername: ${{ secrets.TEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TEST_REGISTRY_PASSWORD }}
          containerAppName: test
          resourceGroup: Scipio
          imageToBuild: scipio.azurecr.io/test:${{ github.sha }}
          dockerfilePath: Dockerfile


